### PR TITLE
Marketing Branding and Frontend Proposals from DotMatrix

### PR DESCRIPTION
**Pull request by nblogist**
Having provided consistent support throughout 2024, DotMatrix is ready to take Darwinia and the Ring ecosystem to new heights in 2025. Our Q1 2025 responsibilities focus on cohesive brand refinement, impactful campaigns, and strategic partnerships, all tracked through transparent monthly reports to ensure measurable progress and sustained community growth.

### CODE REVIEW

**Comment by nblogist** [comment]
CC @hackfisher @fewensa

**Review by hackfisher — APPROVED** [review]
Thanks, @boundless-forest will coordinate with education and websites with you.

cc @boundless-forest @1022ranji 

@1022ranji please help convert/check the 40% part in to RING according to monthly average price, thanks.

**Comment by 1022ranji** [comment]
> Thanks, @boundless-forest will coordinate with education and websites with you.
> 
> cc @boundless-forest @1022ranji
> 
> @1022ranji please help convert/check the 40% part in to RING according to monthly average price, thanks.

Okay, @nblogist The deliverables and reports will be submitted monthly, along with the receive address. I will assist in converting 40% of the average monthly price into RING. Please have @boundless-forest  review the report, and once approved, I will proceed with arranging the payment.

**Comment by nblogist** [comment]
Thanks @1022ranji @hackfisher !! lmk if you need any help or have feedback @boundless-forest

**Pull request merged**
